databases:
  - name: vkdby-db
    databaseName: vkdby_production
    user: vkdby
    plan: free # Note: The free database plan expires after 90 days.
    region: singapore

services:
  - type: web
    name: vkdby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vkdby-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    region: singapore
    plan: free # Web service has a free tier.
